### ISSUE TITLE
Error when retrieving results

### ISSUE THREAD

**Issue by thenecroscope** [JustinGrote/SecretManagement.KeePass#1]
Hi,

I've just been testing out your extension but I'm not having much luck at the minute.

When  I run the get-secret command I can the following error:
**Get-SecretInfo: Unable to get secret information from vault testVault**

I'm running on powershell 7.1.0-rc.1.

I've cloned the repo and install the module fine with no issues. I'm running elevated admin also.

Everything works fine to start with, I can register the vault and then test it fine. As soon as I then get-secretinfo or get-secret I get the above error. 

Any quick fixes I can try. I've tried the verbose parameter but its not giving me any extra info

thanks

**Comment by thenecroscope** [comment]
Ah, Powershell core is not supported by the looks of things. That would explain it

**Comment by JustinGrote** [comment]
@thenecroscope it should be supported by the latest release which uses a new .NET core library.

Unfortunately the new secretmanagement obfuscates the reason for the vault not being found, if you run `$error[0].exception` it will provide more information.

**Comment by thenecroscope** [comment]
Slightly different error now, I now get:
Test-SecretVault: Unable to run Test-SecretVault on vault testVault

ErrorRecord    : Unable to run Test-SecretVault on vault testVault
TargetSite     :
StackTrace     :
Message        : Unable to run Test-SecretVault on vault testVault
Data           : {}
InnerException : System.Management.Automation.CmdletInvocationException: Exception calling ".ctor" with "1"
                 argument(s): "Could not load type 'System.Security.Cryptography.ProtectedMemory' from assembly
                 'System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'."
                  ---> System.Management.Automation.MethodInvocationException: Exception calling ".ctor" with "1"
                 argument(s): "Could not load type 'System.Security.Cryptography.ProtectedMemory' from assembly
                 'System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'."
                  ---> System.TypeLoadException: Could not load type 'System.Security.Cryptography.ProtectedMemory'
                 from assembly 'System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
                    at KeePassLib.Security.ProtectedBinary.Encrypt()
                    at KeePassLib.Security.ProtectedBinary.Init(Boolean bEnableProtection, Byte[] pbData, Int32
                 iOffset, Int32 cbSize)
                    at KeePassLib.Security.ProtectedBinary..ctor(Boolean bEnableProtection, Byte[] pbData)
                    at KeePassLib.Security.ProtectedString.Init(Boolean bEnableProtection, Byte[] pbUtf8)
                    at KeePassLib.Security.ProtectedString..ctor(Boolean bEnableProtection, Byte[] vUtf8Value)
                    at KeePassLib.Keys.KcpPassword.SetKey(Byte[] pbPasswordUtf8)
                    at KeePassLib.Keys.KcpPassword..ctor(String strPassword)
                    --- End of inner exception stack trace ---
                    at System.Management.Automation.DotNetAdapter.AuxiliaryConstructorInvoke(MethodInformation
                 methodInformation, Object[] arguments, Object[] originalArguments)
                    at System.Management.Automation.DotNetAdapter.ConstructorInvokeDotNet(Type type, ConstructorInfo[]
                 constructors, Object[] arguments)
                    at Microsoft.PowerShell.Commands.NewObjectCommand.CallConstructor(Type type, ConstructorInfo[]
                 constructors, Object[] args)
                    --- End of inner exception stack trace ---
                    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
                 funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke
                 clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine,
                 ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis,
                 Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
                    at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope,
                 ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis,
                 Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1
                 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
                    at System.Management.Automation.ScriptBlock.DoInvokeReturnAsIs(Boolean useLocalScope,
                 ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis,
                 Object[] args)
                    at System.Management.Automation.CommandInvocationIntrinsics.InvokeScript(ScriptBlock sb, Boolean
                 useNewScope, PipelineResultTypes writeToPipeline, IList input, Object[] args)
                    at Microsoft.PowerShell.SecretManagement.ExtensionVaultModule.InvokeOnCmdlet(PSCmdlet cmdlet,
                 String script, Object[] args, Exception& terminatingError)
HelpLink       :
Source         :
HResult        : -2146233079

Am I missing a DLL somewhere?

thanks again!

**Comment by JustinGrote** [comment]
@thenecroscope no the module is "busted", I'll push a new update soon once I also fix an issue if you have two secrets with duplicate names

**Comment by JustinGrote** [comment]
@thenecroscope try 0.0.4.1

**Comment by thenecroscope** [comment]
thanks Justin for the speedy responses. I'm caught up with some production issues at the minute, I will have a play with the new version later. thanks again

**Comment by thenecroscope** [comment]
Looking good now, thanks! I tested this last night and it seems to be working well 👍 

Can I pick your brains on a slightly different question if I may. I'm trying to work out how to use a central key vault to store some API values. This is a temporary "quick" solution, not ideal I know.

If I use the keepass vault to store the APIs. I then need a mechanism to store the keepass password within my scripts. I was trying to avoid using certificates. I need to access the scripts from different computers, I could use the -"-SecureKey" param from ConvertFrom-SecureString cmdlet. I'm not really sure I like this approach. Any others options?

**Comment by JustinGrote** [comment]
@thenecroscope if you're on Windows you can store the key in Credential Manager and reference that key. I plan to add some support for these noninteractive scenarios but it will be a while before I have bandwidth.

**Comment by thenecroscope** [comment]
That might work actually in the interim. Thanks!
